package com.tapsouq.sdk.util;

/**
 * Created by dell on 11/28/2016.
 */
public class COUNTRY {

    private static final String[][] code =
            {{"1", "Afghanistan", "AF", "1"},
                    {"2", "Albania", "AL", "1"},
                    {"3", "Algeria", "DZ", "1"},
                    {"4", "American Samoa", "DS", "1"},
                    {"5", "Andorra", "AD", "1"},
                    {"6", "Angola", "AO", "1"},
                    {"7", "Anguilla", "AI", "1"},
                    {"8", "Antarctica", "AQ", "1"},
                    {"9", "Antigua and Barbuda", "AG", "1"},
                    {"10", "Argentina", "AR", "1"},
                    {"11", "Armenia", "AM", "1"},
                    {"12", "Aruba", "AW", "1"},
                    {"13", "Australia", "AU", "4"},
                    {"14", "Austria", "AT", "3"},
                    {"15", "Azerbaijan", "AZ", "1"},
                    {"16", "Bahamas", "BS", "2"},
                    {"17", "Bahrain", "BH", "2"},
                    {"18", "Bangladesh", "BD", "2"},
                    {"19", "Barbados", "BB", "1"},
                    {"20", "Belarus", "BY", "1"},
                    {"21", "Belgium", "BE", "2"},
                    {"22", "Belize", "BZ", "1"},
                    {"23", "Benin", "BJ", "1"},
                    {"24", "Bermuda", "BM", "1"},
                    {"25", "Bhutan", "BT", "1"},
                    {"26", "Bolivia", "BO", "1"},
                    {"27", "Bosnia and Herzegovina", "BA", "1"},
                    {"28", "Botswana", "BW", "1"},
                    {"29", "Bouvet Island", "BV", "1"},
                    {"30", "Brazil", "BR", "2"},
                    {"31", "British Indian Ocean Territory", "IO", "1"},
                    {"32", "Brunei Darussalam", "BN", "1"},
                    {"33", "Bulgaria", "BG", "2"},
                    {"34", "Burkina Faso", "BF", "1"},
                    {"35", "Burundi", "BI", "1"},
                    {"36", "Cambodia", "KH", "1"},
                    {"37", "Cameroon", "CM", "1"},
                    {"38", "Canada", "CA", "4"},
                    {"39", "Cape Verde", "CV", "1"},
                    {"40", "Cayman Islands", "KY", "1"},
                    {"41", "Central African Republic", "CF", "1"},
                    {"42", "Chad", "TD", "1"},
                    {"43", "Chile", "CL", "2"},
                    {"44", "China", "CN", "2"},
                    {"45", "Christmas Island", "CX", "1"},
                    {"46", "Cocos (Keeling) Islands", "CC", "1"},
                    {"47", "Colombia", "CO", "2"},
                    {"48", "Comoros", "KM", "1"},
                    {"49", "Congo", "CG", "1"},
                    {"50", "Cook Islands", "CK", "1"},
                    {"51", "Costa Rica", "CR", "2"},
                    {"52", "Croatia (Hrvatska)", "HR", "2"},
                    {"53", "Cuba", "CU", "1"},
                    {"54", "Cyprus", "CY", "2"},
                    {"55", "Czech Republic", "CZ", "2"},
                    {"56", "Denmark", "DK", "4"},
                    {"57", "Djibouti", "DJ", "1"},
                    {"58", "Dominica", "DM", "1"},
                    {"59", "Dominican Republic", "DO", "2"},
                    {"60", "East Timor", "TP", "1"},
                    {"61", "Ecuador", "EC", "2"},
                    {"62", "Egypt", "EG", "2"},
                    {"63", "El Salvador", "SV", "3"},
                    {"64", "Equatorial Guinea", "GQ", "1"},
                    {"65", "Eritrea", "ER", "1"},
                    {"66", "Estonia", "EE", "3"},
                    {"67", "Ethiopia", "ET", "1"},
                    {"68", "Falkland Islands (Malvinas)", "FK", "1"},
                    {"69", "Faroe Islands", "FO", "1"},
                    {"70", "Fiji", "FJ", "1"},
                    {"71", "Finland", "FI", "3"},
                    {"72", "France", "FR", "3"},
                    {"73", "France, Metropolitan", "FX", "1"},
                    {"74", "French Guiana", "GF", "1"},
                    {"75", "French Polynesia", "PF", "1"},
                    {"76", "French Southern Territories", "TF", "1"},
                    {"77", "Gabon", "GA", "1"},
                    {"78", "Gambia", "GM", "1"},
                    {"79", "Georgia", "GE", "1"},
                    {"80", "Germany", "DE", "4"},
                    {"81", "Ghana", "GH", "2"},
                    {"82", "Gibraltar", "GI", "1"},
                    {"83", "Guernsey", "GK", "1"},
                    {"84", "Greece", "GR", "2"},
                    {"85", "Greenland", "GL", "2"},
                    {"86", "Grenada", "GD", "1"},
                    {"87", "Guadeloupe", "GP", "1"},
                    {"88", "Guam", "GU", "1"},
                    {"89", "Guatemala", "GT", "1"},
                    {"90", "Guinea", "GN", "1"},
                    {"91", "Guinea-Bissau", "GW", "1"},
                    {"92", "Guyana", "GY", "1"},
                    {"93", "Haiti", "HT", "1"},
                    {"94", "Heard and Mc Donald Islands", "HM", "1"},
                    {"95", "Honduras", "HN", "2"},
                    {"96", "Hong Kong", "HK", "3"},
                    {"97", "Hungary", "HU", "3"},
                    {"98", "Iceland", "IS", "3"},
                    {"99", "India", "IN", "1"},
                    {"100", "Isle of Man", "IM", "1"},
                    {"101", "Indonesia", "ID", "2"},
                    {"102", "Iran (Islamic Republic of)", "IR", "1"},
                    {"103", "Iraq", "IQ", "2"},
                    {"104", "Ireland", "IE", "3"},
                    {"105", "Israel", "IL", "3"},
                    {"106", "Italy", "IT", "2"},
                    {"107", "Ivory Coast", "CI", "2"},
                    {"108", "Jersey", "JE", "1"},
                    {"109", "Jamaica", "JM", "2"},
                    {"110", "Japan", "JP", "3"},
                    {"111", "Jordan", "JO", "2"},
                    {"112", "Kazakhstan", "KZ", "1"},
                    {"113", "Kenya", "KE", "2"},
                    {"114", "Kiribati", "KI", "1"},
                    {"115", "Korea, Democratic People's Republic of", "KP", "1"},
                    {"116", "Korea, Republic of", "KR", "1"},
                    {"117", "Kosovo", "XK", "1"},
                    {"118", "Kuwait", "KW", "3"},
                    {"119", "Kyrgyzstan", "KG", "1"},
                    {"120", "Lao People's Democratic Republic", "LA", "1"},
                    {"121", "Latvia", "LV", "2"},
                    {"122", "Lebanon", "LB", "2"},
                    {"123", "Lesotho", "LS", "1"},
                    {"124", "Liberia", "LR", "1"},
                    {"125", "Libyan Arab Jamahiriya", "LY", "1"},
                    {"126", "Liechtenstein", "LI", "1"},
                    {"127", "Lithuania", "LT", "2"},
                    {"128", "Luxembourg", "LU", "2"},
                    {"129", "Macau", "MO", "1"},
                    {"130", "Macedonia", "MK", "2"},
                    {"131", "Madagascar", "MG", "1"},
                    {"132", "Malawi", "MW", "1"},
                    {"133", "Malaysia", "MY", "2"},
                    {"134", "Maldives", "MV", "2"},
                    {"135", "Mali", "ML", "1"},
                    {"136", "Malta", "MT", "2"},
                    {"137", "Marshall Islands", "MH", "1"},
                    {"138", "Martinique", "MQ", "1"},
                    {"139", "Mauritania", "MR", "1"},
                    {"140", "Mauritius", "MU", "2"},
                    {"141", "Mayotte", "TY", "1"},
                    {"142", "Mexico", "MX", "2"},
                    {"143", "Micronesia, Federated States of", "FM", "1"},
                    {"144", "Moldova, Republic of", "MD", "1"},
                    {"145", "Monaco", "MC", "1"},
                    {"146", "Mongolia", "MN", "1"},
                    {"147", "Montenegro", "ME", "1"},
                    {"148", "Montserrat", "MS", "1"},
                    {"149", "Morocco", "MA", "2"},
                    {"150", "Mozambique", "MZ", "1"},
                    {"151", "Myanmar", "MM", "1"},
                    {"152", "Namibia", "NA", "1"},
                    {"153", "Nauru", "NR", "1"},
                    {"154", "Nepal", "NP", "1"},
                    {"155", "Netherlands", "NL", "3"},
                    {"156", "Netherlands Antilles", "AN", "1"},
                    {"157", "New Caledonia", "NC", "1"},
                    {"158", "New Zealand", "NZ", "3"},
                    {"159", "Nicaragua", "NI", "2"},
                    {"160", "Niger", "NE", "1"},
                    {"161", "Nigeria", "NG", "3"},
                    {"162", "Niue", "NU", "1"},
                    {"163", "Norfolk Island", "NF", "1"},
                    {"164", "Northern Mariana Islands", "MP", "1"},
                    {"165", "Norway", "NO", "4"},
                    {"166", "Oman", "OM", "1"},
                    {"167", "Pakistan", "PK", "2"},
                    {"168", "Palau", "PW", "1"},
                    {"169", "Palestine", "PS", "1"},
                    {"170", "Panama", "PA", "2"},
                    {"171", "Papua New Guinea", "PG", "1"},
                    {"172", "Paraguay", "PY", "2"},
                    {"173", "Peru", "PE", "2"},
                    {"174", "Philippines", "PH", "2"},
                    {"175", "Pitcairn", "PN", "1"},
                    {"176", "Poland", "PL", "3"},
                    {"177", "Portugal", "PT", "2"},
                    {"178", "Puerto Rico", "PR", "3"},
                    {"179", "Qatar", "QA", "1"},
                    {"180", "Reunion", "RE", "1"},
                    {"181", "Romania", "RO", "2"},
                    {"182", "Russian Federation", "RU", "1"},
                    {"183", "Rwanda", "RW", "1"},
                    {"184", "Saint Kitts and Nevis", "KN", "1"},
                    {"185", "Saint Lucia", "LC", "1"},
                    {"186", "Saint Vincent and the Grenadines", "VC", "1"},
                    {"187", "Samoa", "WS", "1"},
                    {"188", "San Marino", "SM", "1"},
                    {"189", "Sao Tome and Principe", "ST", "1"},
                    {"190", "Saudi Arabia", "SA", "2"},
                    {"191", "Senegal", "SN", "1"},
                    {"192", "Serbia", "RS", "1"},
                    {"193", "Seychelles", "SC", "1"},
                    {"194", "Sierra Leone", "SL", "1"},
                    {"195", "Singapore", "SG", "3"},
                    {"196", "Slovakia", "SK", "2"},
                    {"197", "Slovenia", "SI", "2"},
                    {"198", "Solomon Islands", "SB", "1"},
                    {"199", "Somalia", "SO", "1"},
                    {"200", "South Africa", "ZA", "3"},
                    {"201", "South Georgia South Sandwich Islands", "GS", "1"},
                    {"202", "Spain", "ES", "3"},
                    {"203", "Sri Lanka", "LK", "2"},
                    {"204", "St. Helena", "SH", "1"},
                    {"205", "St. Pierre and Miquelon", "PM", "1"},
                    {"206", "Sudan", "SD", "1"},
                    {"207", "Suriname", "SR", "1"},
                    {"208", "Svalbard and Jan Mayen Islands", "SJ", "1"},
                    {"209", "Swaziland", "SZ", "1"},
                    {"210", "Sweden", "SE", "3"},
                    {"211", "Switzerland", "CH", "3"},
                    {"212", "Syrian Arab Republic", "SY", "1"},
                    {"213", "Taiwan", "TW", "2"},
                    {"214", "Tajikistan", "TJ", "1"},
                    {"215", "Tanzania, United Republic of", "TZ", "1"},
                    {"216", "Thailand", "TH", "2"},
                    {"217", "Togo", "TG", "1"},
                    {"218", "Tokelau", "TK", "1"},
                    {"219", "Tonga", "TO", "1"},
                    {"220", "Trinidad and Tobago", "TT", "2"},
                    {"221", "Tunisia", "TN", "2"},
                    {"222", "Turkey", "TR", "1"},
                    {"223", "Turkmenistan", "TM", "1"},
                    {"224", "Turks and Caicos Islands", "TC", "1"},
                    {"225", "Tuvalu", "TV", "1"},
                    {"226", "Uganda", "UG", "1"},
                    {"227", "Ukraine", "UA", "1"},
                    {"228", "United Arab Emirates", "AE", "3"},
                    {"229", "United Kingdom", "GB", "4"},
                    {"230", "United States", "US", "4"},
                    {"231", "United States minor outlying islands", "UM", "1"},
                    {"232", "Uruguay", "UY", "2"},
                    {"233", "Uzbekistan", "UZ", "1"},
                    {"234", "Vanuatu", "VU", "1"},
                    {"235", "Vatican City State", "VA", "1"},
                    {"236", "Venezuela", "VE", "2"},
                    {"237", "Vietnam", "VN", "2"},
                    {"238", "Virgin Islands (British)", "VG", "1"},
                    {"239", "Virgin Islands (U.S.)", "VI", "1"},
                    {"240", "Wallis and Futuna Islands", "WF", "1"},
                    {"241", "Western Sahara", "EH", "1"},
                    {"242", "Yemen", "YE", "1"},
                    {"243", "Yugoslavia", "YU", "1"},
                    {"244", "Zaire", "ZR", "1"},
                    {"245", "Zambia", "ZM", "1"},
                    {"0", "Other Country", "01", "1"}};

    public static String[] getCountryInfo(String countryCode) throws CountryCodeException{
        for (int i = 0; i < code.length; i++) {
            if(code[i][2].equalsIgnoreCase(countryCode))
                return code[i];
        }
        throw new CountryCodeException(countryCode + " does not exist in the list of countries.");
    }

    public static String[] getDefaultCountry(){
        return new String[] {"0", "Other Country", "01", "1"};
    }
}
